// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inventory/find/find.proto

package find

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindRequest struct {
	Item                 string           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Qty                  string           `protobuf:"bytes,2,opt,name=qty,proto3" json:"qty,omitempty"`
	Status               string           `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Size                 *FindSizeRequest `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	Tags                 int64            `protobuf:"varint,5,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FindRequest) Reset()         { *m = FindRequest{} }
func (m *FindRequest) String() string { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()    {}
func (*FindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_237344c963741d61, []int{0}
}

func (m *FindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRequest.Unmarshal(m, b)
}
func (m *FindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRequest.Marshal(b, m, deterministic)
}
func (m *FindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRequest.Merge(m, src)
}
func (m *FindRequest) XXX_Size() int {
	return xxx_messageInfo_FindRequest.Size(m)
}
func (m *FindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRequest proto.InternalMessageInfo

func (m *FindRequest) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *FindRequest) GetQty() string {
	if m != nil {
		return m.Qty
	}
	return ""
}

func (m *FindRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *FindRequest) GetSize() *FindSizeRequest {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *FindRequest) GetTags() int64 {
	if m != nil {
		return m.Tags
	}
	return 0
}

type FindSizeRequest struct {
	H                    int64    `protobuf:"varint,1,opt,name=h,proto3" json:"h,omitempty"`
	Ww                   int64    `protobuf:"varint,2,opt,name=ww,proto3" json:"ww,omitempty"`
	Uom                  int64    `protobuf:"varint,3,opt,name=uom,proto3" json:"uom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindSizeRequest) Reset()         { *m = FindSizeRequest{} }
func (m *FindSizeRequest) String() string { return proto.CompactTextString(m) }
func (*FindSizeRequest) ProtoMessage()    {}
func (*FindSizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_237344c963741d61, []int{1}
}

func (m *FindSizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindSizeRequest.Unmarshal(m, b)
}
func (m *FindSizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindSizeRequest.Marshal(b, m, deterministic)
}
func (m *FindSizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindSizeRequest.Merge(m, src)
}
func (m *FindSizeRequest) XXX_Size() int {
	return xxx_messageInfo_FindSizeRequest.Size(m)
}
func (m *FindSizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindSizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindSizeRequest proto.InternalMessageInfo

func (m *FindSizeRequest) GetH() int64 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *FindSizeRequest) GetWw() int64 {
	if m != nil {
		return m.Ww
	}
	return 0
}

func (m *FindSizeRequest) GetUom() int64 {
	if m != nil {
		return m.Uom
	}
	return 0
}

type FindResponse struct {
	Item                 string   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Qty                  string   `protobuf:"bytes,2,opt,name=qty,proto3" json:"qty,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindResponse) Reset()         { *m = FindResponse{} }
func (m *FindResponse) String() string { return proto.CompactTextString(m) }
func (*FindResponse) ProtoMessage()    {}
func (*FindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_237344c963741d61, []int{2}
}

func (m *FindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindResponse.Unmarshal(m, b)
}
func (m *FindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindResponse.Marshal(b, m, deterministic)
}
func (m *FindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindResponse.Merge(m, src)
}
func (m *FindResponse) XXX_Size() int {
	return xxx_messageInfo_FindResponse.Size(m)
}
func (m *FindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindResponse proto.InternalMessageInfo

func (m *FindResponse) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *FindResponse) GetQty() string {
	if m != nil {
		return m.Qty
	}
	return ""
}

func (m *FindResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*FindRequest)(nil), "FindRequest")
	proto.RegisterType((*FindSizeRequest)(nil), "FindSizeRequest")
	proto.RegisterType((*FindResponse)(nil), "FindResponse")
}

func init() { proto.RegisterFile("inventory/find/find.proto", fileDescriptor_237344c963741d61) }

var fileDescriptor_237344c963741d61 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x71, 0x1c, 0x8a, 0xb8, 0x06, 0xa8, 0x6e, 0x40, 0x86, 0x29, 0x8a, 0x18, 0x32, 0x19,
	0x54, 0x7e, 0x01, 0x0b, 0x2c, 0x4c, 0xe6, 0x17, 0x14, 0xf5, 0xa0, 0x1e, 0x6a, 0xb7, 0xf5, 0x05,
	0xab, 0xdd, 0xf9, 0xdf, 0xc8, 0x47, 0x87, 0x88, 0x95, 0xc5, 0xfa, 0x7c, 0xb6, 0xde, 0x7b, 0xf7,
	0xe0, 0xc6, 0x87, 0x2f, 0x0a, 0x1c, 0x77, 0xfb, 0xfb, 0x0f, 0x1f, 0x96, 0x72, 0xd8, 0xcd, 0x2e,
	0x72, 0xec, 0xbe, 0x15, 0x4c, 0x9f, 0x7d, 0x58, 0x3a, 0xda, 0x0e, 0x94, 0x18, 0x11, 0x6a, 0xcf,
	0xb4, 0x36, 0xaa, 0x55, 0xfd, 0xb9, 0x13, 0xc6, 0x19, 0xe8, 0x2d, 0xef, 0x4d, 0x25, 0xa3, 0x82,
	0x78, 0x0d, 0x93, 0xc4, 0x0b, 0x1e, 0x92, 0xd1, 0x32, 0x3c, 0xde, 0xf0, 0x0e, 0xea, 0xe4, 0x0f,
	0x64, 0xea, 0x56, 0xf5, 0xd3, 0xf9, 0xcc, 0x16, 0xe5, 0x37, 0x7f, 0xa0, 0xa3, 0xba, 0x93, 0xd7,
	0xe2, 0xc1, 0x8b, 0xcf, 0x64, 0x4e, 0x5b, 0xd5, 0x6b, 0x27, 0xdc, 0x3d, 0xc1, 0xd5, 0x9f, 0xcf,
	0xd8, 0x80, 0x5a, 0x49, 0x0e, 0xed, 0xd4, 0x0a, 0x2f, 0xa1, 0xca, 0x59, 0x32, 0x68, 0x57, 0xe5,
	0x5c, 0x42, 0x0d, 0x71, 0x2d, 0xfe, 0xda, 0x15, 0xec, 0x5e, 0xa1, 0xf9, 0xdd, 0x24, 0x6d, 0x62,
	0x48, 0xf4, 0xbf, 0x55, 0xe6, 0x0f, 0x50, 0x17, 0x35, 0xec, 0xe1, 0xec, 0x85, 0x58, 0xb0, 0xb1,
	0xa3, 0xa6, 0x6e, 0x2f, 0xec, 0xd8, 0xad, 0x3b, 0x79, 0x9f, 0x48, 0xa3, 0x8f, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x62, 0xf5, 0xdf, 0xb6, 0x6e, 0x01, 0x00, 0x00,
}
